# Generated by Django 5.2.8 on 2025-11-19 06:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('req_side', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='req',
            name='mount',
            field=models.IntegerField(),
        ),
    ]
