# Generated by Django 5.2.8 on 2025-11-19 06:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('req_side', '0002_alter_req_mount'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='req',
            new_name='Member',
        ),
    ]
