# Generated by Django 5.2.8 on 2025-11-19 09:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('req_side', '0003_rename_req_member'),
    ]

    operations = [
        migrations.RenameField(
            model_name='member',
            old_name='mount',
            new_name='amount',
        ),
    ]
