# Generated by Django 5.2.8 on 2025-11-19 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('req_side', '0004_rename_mount_member_amount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='name',
            field=models.CharField(max_length=30),
        ),
    ]
