# Generated by Django 5.2.8 on 2025-11-19 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('req_side', '0005_alter_member_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='name',
            field=models.CharField(max_length=50),
        ),
    ]
