# Generated by Django 5.2.8 on 2025-11-19 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('req_side', '0006_alter_member_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Per',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('usn', models.CharField(max_length=20)),
                ('psw', models.CharField(max_length=20)),
            ],
        ),
    ]
